### PR TITLE
Fix #165.

### LINKED ISSUE #165: NullPointerException on enable
I'm using

CraftBukkit version git-Bukkit-jenkins-CraftBukkit-93 (MC: 1.2.5) (Implementing API version 1.2.5-R1.3-MCPC-SNAPSHOT)

By Tekkit 3.0.3 - http://www.technicpack.net/tekkit/

And can't enable the plugin.

2012-05-29 11:53:12 [INFO] [SpaceBukkit] Enabling SpaceBukkit v0.1
2012-05-29 11:53:12 [SEVERE] Error occurred while enabling SpaceBukkit v0.1 (Is it up to date?)
java.lang.NullPointerException
    at me.neatmonster.spacebukkit.plugins.PluginsManager.getJAR(PluginsManager.java:33)
    at me.neatmonster.spacebukkit.plugins.PluginsManager.<init>(PluginsManager.java:61)
    at me.neatmonster.spacebukkit.SpaceBukkit.onEnable(SpaceBukkit.java:89)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:386)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:262)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:244)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:375)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:362)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:191)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

### PR DESCRIPTION
**Pull request by roblabla**
In function GetJAR, check if the Plugin's PluginLoader is the 
JavaPluginLoader class. If it isn't, return null. 
This way, if there is custom plugin loaders installed (Such as PythonPluginLoader (http://dev.bukkit.org/server-mods/Python-Plugin-Loader/ ) or _maybe_ tekkit/modloadermp (untested)), there will be no errors and the Plugins page will load correctly.

### CODE REVIEW

**Comment by roblabla** [comment]
Of course. It is currently loaded on my test server, and the plugin page can load (it couldn't load before). It still shows the custom plugins in the plugin list, and I would suppose unloading them works, looking at the code (untested, will do if necessary). The catch is that it doesn't add a 
Plugin:File
line in the jars.yml file. I suppose you use this for loading, and since there's no file in there, loading would probably throw an exception (didn't test this either, will do.).

I would like to add I don't have a tekkit/modloadermp server right now, so I can't test this. But it would seem logical from a coding point of view that it would also fix it, unless they also use the JavaPluginLoader. Don't really know, I'll investigate.

**Comment by tips48** [comment]
Alright, testing it with Tekkit is going to be what we need to do. Although this is smart, we still need to see if it works on Tekkit

**Comment by roblabla** [comment]
I have good and bad news. The good news is, the plugins page DOES load and stops hanging the whole thing. The bad news is, pluginInformation is Empty, and it outputs some errors in the console. Line 429 of serveraction, that leads to 

``` java
            pluginInformations.put("DataFolder", plugin.getDataFolder().getPath());
```

It's 1:30 AM right now, so I think I'll go to sleep. Tomorow, I'll dive into ModloaderMP's source and see if I can get at least the BASIC Plugin information out (like the name would be the bare minimum, right now it just returns an empty string).

**Comment by tips48** [comment]
Awesome, thanks for testing. Can you paste the exact NPE? We can look at the issue

**Comment by roblabla** [comment]
The NPE was : 
[SEVERE] java.lang.reflect.InvocationTargetException
[SEVERE]    at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
[SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
[SEVERE]    at me.neatmonster.spacemodule.api.ActionsManager.invoke(ActionsManager.java:140)
[SEVERE]    at me.neatmonster.spacemodule.api.ActionsManager.execute(ActionsManager.java:123)
[SEVERE]    at me.neatmonster.spacebukkit.PanelListener.interpret(PanelListener.java:56)
[SEVERE]    at me.neatmonster.spacebukkit.PanelListener.run(PanelListener.java:140)
[SEVERE] Caused by: java.lang.NullPointerException
[SEVERE]    at me.neatmonster.spacebukkit.actions.ServerActions.getPluginInformations(ServerActions.java:429)
[SEVERE]    ... 7 more
I suppose ModLoaderMP's plugins doesn't implement getDataFolder.
I fixed it in latest commit. I simply added 

``` java
try{
    pluginInformations.put("DataFolder", plugin.getDataFolder().getPath());
} catch (NullPointerException e) {
    pluginInformations.put("DataFolder", "NONE");
}
```

I tested this, and for the tekkit/modloadermp mods, it shows the mod name (e.g. : mod_AdditionalPipes) under plugin name, it marks them as enabled, and under version, it says "ForgeMod". 
Trying to unload/remove doesn't work on forgemods, but it doesn't throw exceptions or whatever. 

PS : is it be possible to disable the automatic spacebukkit updating each time we start the wrapper, it's really annoying...

**Comment by tips48** [comment]
How about having the default DataFolder be "plugins/" or "plugins"

**Comment by tips48** [comment]
and yes it is, turn off development and recommended in the configuration (SpaceModule/configuration.yml)

**Comment by roblabla** [comment]
tips48, the idea is that if it's NONE, the webinterface can catch it and remove the buttons of the broken functionality (configure). Besides, forgemods are not installed in plugins/ so it wouldn't really make sense IMO.

On another note, I won't try to edit the webinterface as PHP is not my cup of tea. I'll still look into tekkit to see if it's possible to get the configuration folder, but I think each mod can chose where it is, so I suppose it will be vain for me to try this... 
PS : sorry about close/reopen. I failed at clicking the right button (facepalm)

**Comment by tips48** [comment]
That's fine ;) 
And I'm just thinking that if we default to "plugins" it will work 99.9% of the time and won't break functionality

**Comment by roblabla** [comment]
If you want to test without having to compile : 
https://github.com/roblabla/SpaceBukkit/downloads
Those are my changes, compiled.

Hmm, I see what you mean tips48, but right now, if you default to NONE, it will quiet simply not do anything.
PS : Are you on an irc channel or something, might get things done faster if we can chat directly.  I'm on http://forums.xereo.net/chat/

**Comment by roblabla** [comment]
This should compile now, and it doesn't throw the NPE anymore, I use if/else block to capture it.

**Comment by tips48** [comment]
Looks nicer now

**Comment by drdanick** [comment]
We have provided our own fix for this issue, which includes fixes for a few corner cases.

**Pull request closed without merging**
