### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by tips48**
- Update to the new Configuration
- Add .gitignore
- Conversions from SpaceBukkit.getInstance() to SpaceBukkit.STATIC_MEMBER
- General Cleanup

### CODE REVIEW

**Comment by AgentOak** [comment]
The preferred way to output messages is JavaPlugin#getLogger(), which returns a PluginLogger that automatically prefixes your messages with the plugin's name or (optional) a defined prefix in plugin.yml.

**Comment by tips48** [comment]
Yes, I know..I'm looking into that at the moment.

**Comment by drdanick** [comment]
I agree with Marco01809.

If you are willing to correct this, we will keep the pull request on hold until then.

**Comment by iVMoRiginal** [comment]
When will inventory viewing be added? Or does it already exist in a commit? I've not seen it, last I heard it was broken :P

**Comment by tips48** [comment]
Sure, I'll correct it.
@iVMoRiginal I have no clue...I haven't modified it at all personally!

EDIT: Done with updating it

**Pull request closed without merging**
